### ISSUE TITLE
16. FAÇA UM LAYOUT PARA O SITE - Prioridade 5

### ISSUE THREAD

**Issue by herculesgabriel** [mustang-roy/market-front-end#1]

**Comment by herculesgabriel** [comment]
Falta um menu drop-down para ordenação dos itens do menor para o maior preço e do maior para o menor preço.

@danwhat

**Comment by danwhat** [comment]
Apontar os acertos ninguem quer né?

**Comment by danwhat** [comment]
Ta feito.
