### ISSUE TITLE
7. CLICAR NA EXIBIÇÃO RESUMIDA DE UM PRODUTO E IR PARA UMA TELA COM SUA EXIBIÇÃO DETALHADA - Prioridade 3

### ISSUE THREAD

**Issue by herculesgabriel** [mustang-roy/market-front-end#3]

**Comment by herculesgabriel** [comment]
Comportamento: clicar no card do produto leva à página de exibição detalhada do produto, com nome do produto, imagem, preço e especificação técnica. A tela também deve possuir um botão que leve ao carrinho de compras.

**Comment by herculesgabriel** [comment]
#6

**Comment by herculesgabriel** [comment]
@danwhat , é preciso adicionar o botão que leva ao carrinho de compras na página de detalhes do produto conforme imagem  [desse link](https://github.com/tryber/sd-06-project-frontend-online-store/blob/master/wireframes/card_07.png).

**Comment by danwhat** [comment]
@herculesgabriel Done
